spring.datasource.url=${IMJANGBOX_DB_URL}
spring.datasource.username=${IMJANGBOX_DB_USERNAME}
spring.datasource.password=${IMJANGBOX_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=never
mybatis.mapper-locations=classpath:/mappers/**/*.xml
